name: ci-pipeline-pure

on:
  pull_request:
    branches: [main]
  push:
    branches: 
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  ci_pure_pipeline:
    if: false # Comment this line to enable this workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run test
        run: make docker-test

      - name: Build docker image
        run: make docker-build

      - name: Log in to Docker Hub
        if: ${{ github.event_name != 'pull_request' }}
        run: make docker-login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push docker image
        if: ${{ github.event_name != 'pull_request' }}
        run: make docker-release